//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAPPClient.MyWFCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWFCService.ITeachService")]
    public interface ITeachService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeachService/GetServerName", ReplyAction="http://tempuri.org/ITeachService/GetServerNameResponse")]
        string GetServerName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeachService/GetServerName", ReplyAction="http://tempuri.org/ITeachService/GetServerNameResponse")]
        System.Threading.Tasks.Task<string> GetServerNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeachService/GetServerByName", ReplyAction="http://tempuri.org/ITeachService/GetServerByNameResponse")]
        string GetServerByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeachService/GetServerByName", ReplyAction="http://tempuri.org/ITeachService/GetServerByNameResponse")]
        System.Threading.Tasks.Task<string> GetServerByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITeachServiceChannel : WCFAPPClient.MyWFCService.ITeachService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeachServiceClient : System.ServiceModel.ClientBase<WCFAPPClient.MyWFCService.ITeachService>, WCFAPPClient.MyWFCService.ITeachService {
        
        public TeachServiceClient() {
        }
        
        public TeachServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeachServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeachServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeachServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetServerName() {
            return base.Channel.GetServerName();
        }
        
        public System.Threading.Tasks.Task<string> GetServerNameAsync() {
            return base.Channel.GetServerNameAsync();
        }
        
        public string GetServerByName(string name) {
            return base.Channel.GetServerByName(name);
        }
        
        public System.Threading.Tasks.Task<string> GetServerByNameAsync(string name) {
            return base.Channel.GetServerByNameAsync(name);
        }
    }
}
